#!/bin/bash
    UNTRACK=`git ls-files --exclude-standard --others 2>/dev/null|gwc -l`
    MODIFIED=`git diff --name-only 2>/dev/null|gwc -l`
    INDEX=`git diff --cached --name-only 2>/dev/null | gwc -l`
    U="";
    M="";
    I="";
    BRANCH=`git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/'`

    if [ $UNTRACK -ne "0" ];then U="\033[36mnew=${UNTRACK}\033[0m";fi
    if [ $MODIFIED -ne "0" ];then M="\033[34mmodified=${MODIFIED}\033[0m";fi
    if [ $INDEX -ne "0" ];then I="\033[33mstaged=${INDEX}\033[0m";fi
    
    UP_ARROW='\xE2\x86\x91'
    DOWN_ARROW='\xE2\x86\x93'
    REMOTE=`git remote 2>/dev/null | head -1`
    AHEAD=`git rev-list $REMOTE/$BRANCH..HEAD 2>/dev/null|gwc -l`
    BEHIND=`git rev-list HEAD..$REMOTE/$BRANCH 2>/dev/null|gwc -l`
    RET="\033[0m"

    if [ $AHEAD -ne "0" ] ; then
            RET="$RET\033[38;5;14m$AHEAD${UP_ARROW}\033[0m";
    fi
    if [ $AHEAD -ne "0" ] && [ $BEHIND -ne "0" ] ; then
            RET="$RET \033[38;5;129m$BEHIND${DOWN_ARROW}\033[0m";
        else 
         if [ $BEHIND -ne "0" ];then
            RET="\033[38;5;129m$BEHIND${DOWN_ARROW}\033[0m"
         fi;
    fi
   

    if [ -n "$BRANCH" ];then
        if [ $AHEAD -ne "0" ] || [ $BEHIND -ne "0" ] ; then
            echo -ne "\n\033[31mremote ($REMOTE/$BRANCH)\033[0m : $RET"
        fi
        if [ $UNTRACK -ne "0" ] || [ $MODIFIED -ne "0" ] || [ $INDEX -ne "0" ];then
            echo -ne "\n\033[38;5;129mgit status ( "
            if [ $INDEX -ne "0" ];then
                echo -ne "$I "
            fi
            if [ $MODIFIED -ne "0" ];then
                echo -ne "$M "
            fi
            if [ $UNTRACK -ne "0" ];then
                echo -ne "$U "
            fi
            echo -ne "\033[38;5;129m)\n"
        fi
    fi

