#! /bin/bash   
set -m
PARALLEL=0
MAX_PARALLEL=5
for i in `ls -d ./*/` ; 
    do pushd $i;
        git up &
		let "PARALLEL++"
		if [[  "$PARALLEL" -ge "$MAX_PARALLEL" ]]; then
			fg
		fi	
    popd;
done
fg
